controllers/ComparisonController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Comparison;
use app\models\ComparisonSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ComparisonController implements the CRUD actions for Comparison model.
 */
class ComparisonController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Comparison models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ComparisonSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Comparison model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Comparison model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Comparison();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->Comp_ID]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Comparison model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->Comp_ID]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Comparison model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Comparison model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Comparison the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Comparison::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/DiagramsController.php
<?php


namespace app\controllers;
use kartik\mpdf\Pdf;
use \Mpdf\Mpdf;

class DiagramsController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }
    public function actionStudiesByYear()
    {
        return $this->render('studies-by-year');
    }
    public function actionSpeciesWordcloud()
    {
        return $this->render('species-wordcloud');
    }
    public function actionJournalWordcloud()
    {
        return $this->render('journal-wordcloud');
    }
    public function actionExperimentsPerStudy()
    {
        return $this->render('experiments-per-study');
    }
    public function actionTree()
    {
        return $this->render('tree');
    }
    public function actionWos()
    {
        return $this->render('wos');
    }
    public function actionHistoricalNetwork()
    {
        return $this->render('historical-network');
    }

	public function actionThematicMap()
    {
        return $this->render('thematic-map');
    }

	public function actionTopicNetwork()
    {
        return $this->render('topic-network');
    }

	public function actionCollaborationNetwork()
    {
        return $this->render('collaboration-network');
    }


    public function actionCollaborations()
    {
        $pdf = new mPDF();
        $pdf->WriteHTML('Hello World');

        $pdf->Output();

    }

}

controllers/SampleSizeYearSexController.php
<?php

namespace app\controllers;

use Yii;
use app\models\SampleSizeYearSex;
use app\models\SampleSizeYearSexSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SampleSizeYearSexController implements the CRUD actions for SampleSizeYearSex model.
 */
class SampleSizeYearSexController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all SampleSizeYearSex models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SampleSizeYearSexSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single SampleSizeYearSex model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new SampleSizeYearSex model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new SampleSizeYearSex();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->study_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing SampleSizeYearSex model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->study_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing SampleSizeYearSex model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the SampleSizeYearSex model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return SampleSizeYearSex the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = SampleSizeYearSex::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/StudyInfoController.php
<?php

namespace app\controllers;

use Yii;
use app\models\StudyInfo;
use app\models\StudyInfoSearch;
use app\models\ExperimentsPerStudy;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use app\models\CountryCodesOfFirstAuthors;


/**
 * StudyInfoController implements the CRUD actions for StudyInfo model.
 */
class StudyInfoController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all StudyInfo models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new StudyInfoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionIndexYear($year)
    {
        $searchModel = new StudyInfoSearch();
        $searchModel->Year = $year;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);



        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionIndexExperiments($lower, $higher)
    {
        $higher = $higher - 1;
        $lower = $lower+1;
        $materials = ExperimentsPerStudy::find()->where('experiments = '. $lower )->all();
        $ids = [];
        foreach ($materials as $material) {
            array_push($ids, $material['study_id']);
        }

        $searchModel = new StudyInfoSearch();


        $query = StudyInfo::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);


        $query->andFilterWhere(['in', 'study_ID', $ids]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

	public function actionIndexFirstAuthorCountry($country)
    {
        $materials = CountryCodesOfFirstAuthors::find()->where('country_code = \''. $country. '\'')->all();
        $ids = [];
        foreach ($materials as $material) {
            array_push($ids, $material['study_id']);
        }

        $searchModel = new StudyInfoSearch();


        $query = StudyInfo::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);


        $query->andFilterWhere(['in', 'study_ID', $ids]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }





    /**
     * Displays a single StudyInfo model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new StudyInfo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new StudyInfo();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->study_ID]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing StudyInfo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->study_ID]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing StudyInfo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the StudyInfo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return StudyInfo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = StudyInfo::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            [
                'label' => 'Data',
                'items' => [


                    ['label' => 'Comparisons', 'url' => ['/comparison/index']],
                    ['label' => 'Studies', 'url' => ['/study-info/index']],






                ],
            ],
            [
                'label' => 'Graphical Summaries',
                'items' => [


                    '<li class="divider"></li>',
                    '<li class="dropdown-header">Publication information</li>',
                    ['label' => 'Studies per year', 'url' => ['/diagrams/studies-by-year']],
                    ['label' => 'Wordcloud of journals', 'url' => ['/diagrams/journal-wordcloud']],
                    ['label' => 'Geographical distribution of studies', 'url' => ['/studies-per-country/index']],
                    ['label' => 'Diagrams from Web of Science', 'url' => ['/diagrams/wos']],
                    
                    '<li class="divider"></li>',
                    '<li class="dropdown-header">Bibliographics</li>',
                    ['label' => 'Collaboration network', 'url' => ['/diagrams/collaboration-network']],
                    ['label' => 'Historical network', 'url' => ['/diagrams/historical-network']],
                    ['label' => 'Topic network', 'url' => ['/diagrams/topic-network']],
                    ['label' => 'Thematic map', 'url' => ['/diagrams/thematic-map']],
                    
                    
                    '<li class="divider"></li>',
                    '<li class="dropdown-header">Studies and comparisons</li>',
                    ['label' => 'Experiments per study', 'url' => ['/diagrams/experiments-per-study']],
                    ['label' => 'Sample sizes over the years', 'url' => ['/sample-size-year-sex/index']],
                    ['label' => 'Wordcloud of species', 'url' => ['/diagrams/species-wordcloud']],
                    ['label' => 'Phylogenetic tree', 'url' => ['/diagrams/tree']],





                   








                ],
            ],
       
        ],
    ]);
    NavBar::end();

    $this->registerLinkTag(['rel' => 'icon', 'type' => 'image/png', 'href' => 'https://researchweaving.com/rw.png']);
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left"><a href="https://www.researchweaving.com/">Research Weaving</a> </p>
        <p class="pull-right">&copy; <a href="http://www.i-deel.org/">I-DEEL</a> <?= date('Y') ?></p>
    </div>
</footer>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>