models/StudiesPerCountry.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "studies_per_country".
 *
 * @property string $country
 * @property string $country_code
 * @property int $studies
 */
class StudiesPerCountry extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'studies_per_country';
    }

    public static function primaryKey()
    {
        return ['country'];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['studies'], 'integer'],
            [['country'], 'string', 'max' => 20],
            [['country_code'], 'string', 'max' => 5],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'country' => 'Country',
            'country_code' => 'Country Code',
            'studies' => 'Studies',
        ];
    }
}

controllers/StudiesPerCountryController.php
<?php

namespace app\controllers;

use Yii;
use app\models\StudiesPerCountry;
use app\models\StudiesPerCountrySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * StudiesPerCountryController implements the CRUD actions for StudiesPerCountry model.
 */
class StudiesPerCountryController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all StudiesPerCountry models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new StudiesPerCountrySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single StudiesPerCountry model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new StudiesPerCountry model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new StudiesPerCountry();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->country]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing StudiesPerCountry model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->country]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing StudiesPerCountry model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the StudiesPerCountry model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return StudiesPerCountry the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = StudiesPerCountry::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/StudyInfoController.php
<?php

namespace app\controllers;

use Yii;
use app\models\StudyInfo;
use app\models\StudyInfoSearch;
use app\models\ExperimentsPerStudy;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use app\models\CountryCodesOfFirstAuthors;


/**
 * StudyInfoController implements the CRUD actions for StudyInfo model.
 */
class StudyInfoController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all StudyInfo models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new StudyInfoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionIndexYear($year)
    {
        $searchModel = new StudyInfoSearch();
        $searchModel->Year = $year;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);



        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionIndexExperiments($lower, $higher)
    {
        $higher = $higher - 1;
        $lower = $lower+1;
        $materials = ExperimentsPerStudy::find()->where('experiments = '. $lower )->all();
        $ids = [];
        foreach ($materials as $material) {
            array_push($ids, $material['study_id']);
        }

        $searchModel = new StudyInfoSearch();


        $query = StudyInfo::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);


        $query->andFilterWhere(['in', 'study_ID', $ids]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

	public function actionIndexFirstAuthorCountry($country)
    {
        $materials = CountryCodesOfFirstAuthors::find()->where('country_code = \''. $country. '\'')->all();
        $ids = [];
        foreach ($materials as $material) {
            array_push($ids, $material['study_id']);
        }

        $searchModel = new StudyInfoSearch();


        $query = StudyInfo::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);


        $query->andFilterWhere(['in', 'study_ID', $ids]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }





    /**
     * Displays a single StudyInfo model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new StudyInfo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new StudyInfo();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->study_ID]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing StudyInfo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->study_ID]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing StudyInfo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the StudyInfo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return StudyInfo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = StudyInfo::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/studies-per-country/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\StudiesPerCountry */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="studies-per-country-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'country')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'country_code')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'studies')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/studies-per-country/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\StudiesPerCountrySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="studies-per-country-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'country') ?>

    <?= $form->field($model, 'country_code') ?>

    <?= $form->field($model, 'studies') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/studies-per-country/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\StudiesPerCountry */

$this->title = 'Create Studies Per Country';
$this->params['breadcrumbs'][] = ['label' => 'Studies Per Countries', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="studies-per-country-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/studies-per-country/index.php
<head>
<style type="text/css">
 p.MsoNormal
	{margin-bottom:.0001pt;
	text-align:justify;
	text-justify:inter-ideograph;
	font-size:10.5pt;
	font-family:"Calibri",sans-serif;
	margin-left: 0cm;
	margin-right: 0cm;
	margin-top: 0cm;
}
.auto-style1 {
	font-size: large;
}
</style>
</head>

<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\grid\GridView;
use app\models\CountriesOfFirstAuthors;
use yii\data\ActiveDataProvider;

use miloschuman\highcharts\Highmaps;
use yii\web\JsExpression;
use app\models\StudiesPerCountry;

/* @var $this yii\web\View */
/* @var $searchModel app\models\StudiesPerCountrySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Geographical distribution of studies';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="studies-per-country-index">

    <h3><?= Html::encode($this->title) ?></h3>
    <p class="MsoNormal">
	<span class="auto-style1" style="font-family: &quot;Helvetica Neue&quot;; mso-fareast-font-family: &quot;Times New Roman&quot;; mso-bidi-font-family: &quot;Times New Roman&quot;; color: #333333; background: white; mso-font-kerning: 0pt; mso-ansi-language: EN-AU; mso-fareast-language: EN-US">
	Geographical distribution of the affiliation countries of the first authors 
	of the included studies. The intensity of the shading is proportional to the 
	number of first authors affiliated to a given country.<o:p><br><em>You 
	can click on each country to obtain the filtered list of corresponding 
	review articles.</em></o:p></span></p>
	<p class="MsoNormal">
	<o:p></o:p>
	</p>
	<p class="MsoNormal">
	<o:p></o:p>
	</p>
	<p class="MsoNormal">
	<o:p><br></o:p>
	</p>
	<p class="MsoNormal">
	<o:p></o:p>
	</p>
	<p class="MsoNormal">
	<o:p></o:p>
	</p>
	<p class="MsoNormal">
	<o:p></o:p></p>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>


    <?php
    $countries = StudiesPerCountry::find()
        ->asArray()
        ->all();



    #print_r($subject_ids);
    #print(count($subject_ids));



    ?>

    <?php
    $i = 0;
    foreach ($countries as $country) {
        $data[$i] = [$country['country_code'], $country['studies']];
        $i = $i + 1;
    }
    $this->registerJsFile('https://code.highcharts.com/mapdata/custom/world.js', [
        'depends' => 'miloschuman\highcharts\HighchartsAsset'
    ]);

   


    ?>














  <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://code.highcharts.com/maps/highmaps.js"></script>
    <script src="https://code.highcharts.com/maps/modules/data.js"></script>
    <script src="https://code.highcharts.com/maps/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/maps/modules/offline-exporting.js"></script>
    <script src="https://code.highcharts.com/mapdata/custom/world.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>

    <div id="container" style="height: 600px; min-width: 310px; max-width: 1200px; margin: 0 auto"></div>


    <script>


        $.getJSON('https://cdn.rawgit.com/highcharts/highcharts/057b672172ccc6c08fe7dbb27fc17ebca3f5b770/samples/data/world-population.json', function (data) {
            data_array = <?php echo json_encode($data);?>;

            console.log(data);
            console.log(data_array);
            Highcharts.mapChart('container', {
                chart: {
                    borderWidth: 0,
                    map: 'custom/world'
                },

                title: {
                    text: ''
                },

                subtitle: {
                    text: ''
                },

                legend: {
                    enabled: true,
                    layout: 'vertical',
                    align: 'left',
                    verticalAlign: 'bottom'
                },

                mapNavigation: {
                    enabled: true,
                    buttonOptions: {
                        verticalAlign: 'bottom'
                    }
                },
                colorAxis: {
                    min: 1,
                    max:20,
                    type: 'logarithmic',
                    maxColor: '#1E8312'
                },

                series: [{
                    name: 'countries',
                    color: '#E0E0E0',
                    enableMouseTracking: false
                }, {
                    name: 'studies',
                    joinBy: 'hc-key',
                    data: data_array,
                    minSize: 5,
                    maxSize: '20%',
                    tooltip: {
                        pointFormat: '{point.properties.name}: {point.value}'
                    },
                    dataLabels: {
                        enabled: true,
                        style: {
                            fontSize: '15px'
                        }
                    },
                    events: {
                        click: function (event) {
                            if (event.point.value == 0)  {
                                alert("No studies found!");
                            }
                            else {
                                var country = event.point.properties['hc-key'];
                                console.log(event.point);
                                var url_to = <?php echo json_encode(Url::to(['study-info/index-first-author-country'])); ?>;
                                //console.log(url_to);
                                var new_url = url_to.concat('&country=', country);
                                var win = window.open(new_url, '_blank');
                                win.focus();
                            }

                        }
                    },
                }]
            });
        });

    </script>

</div>

views/studies-per-country/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\StudiesPerCountry */

$this->title = 'Update Studies Per Country: {nameAttribute}';
$this->params['breadcrumbs'][] = ['label' => 'Studies Per Countries', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->country, 'url' => ['view', 'id' => $model->country]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="studies-per-country-update">

    <h4><?= Html::encode($this->title) ?></h4>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/studies-per-country/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\StudiesPerCountry */

$this->title = 'Studies from '.$model->country;
$this->params['breadcrumbs'][] = ['label' => 'Studies Per Countries', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="studies-per-country-view">

    <h3><?= Html::encode($this->title) ?></h3>


    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'country',
            'country_code',
            'studies',
        ],
    ]) ?>

</div>